### ISSUE TITLE
List functions fail on new iocage installation

### ISSUE THREAD

**Issue by amendlik** [bougie/salt-iocage-formula#7]
All three list functions produce a stack trace on a new system with no jails.

FreeBSD 11.1-RELEASE-p10 with iocage 0.9.10

```
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.freebsd_e98484_salt/salt-call", line 15, in <module>
            salt_call()
          File "/var/tmp/.freebsd_e98484_salt/py2/salt/scripts.py", line 391, in salt_call
            client.run()
          File "/var/tmp/.freebsd_e98484_salt/py2/salt/cli/call.py", line 58, in run
            caller.run()
          File "/var/tmp/.freebsd_e98484_salt/py2/salt/cli/caller.py", line 134, in run
            ret = self.call()
          File "/var/tmp/.freebsd_e98484_salt/py2/salt/cli/caller.py", line 204, in call
            ret['return'] = func(*args, **kwargs)
          File "/var/tmp/.freebsd_e98484_salt/running_data/var/cache/salt/minion/extmods/modules/iocage.py", line 161, in list_jails
            return _display_list(_list())
          File "/var/tmp/.freebsd_e98484_salt/running_data/var/cache/salt/minion/extmods/modules/iocage.py", line 107, in _list
            if len(_) > 0])
          File "/var/tmp/.freebsd_e98484_salt/running_data/var/cache/salt/minion/extmods/modules/iocage.py", line 106, in <dictcomp>
            headers[k]: v for k, v in enumerate([_ for _ in l.split(' ')
        IndexError: list index out of range

    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.freebsd_e98484_salt/salt-call", line 15, in <module>
            salt_call()
          File "/var/tmp/.freebsd_e98484_salt/py2/salt/scripts.py", line 391, in salt_call
            client.run()
          File "/var/tmp/.freebsd_e98484_salt/py2/salt/cli/call.py", line 58, in run
            caller.run()
          File "/var/tmp/.freebsd_e98484_salt/py2/salt/cli/caller.py", line 134, in run
            ret = self.call()
          File "/var/tmp/.freebsd_e98484_salt/py2/salt/cli/caller.py", line 204, in call
            ret['return'] = func(*args, **kwargs)
          File "/var/tmp/.freebsd_e98484_salt/running_data/var/cache/salt/minion/extmods/modules/iocage.py", line 174, in list_templates
            return _display_list(_list('-t'))
          File "/var/tmp/.freebsd_e98484_salt/running_data/var/cache/salt/minion/extmods/modules/iocage.py", line 107, in _list
            if len(_) > 0])
          File "/var/tmp/.freebsd_e98484_salt/running_data/var/cache/salt/minion/extmods/modules/iocage.py", line 106, in <dictcomp>
            headers[k]: v for k, v in enumerate([_ for _ in l.split(' ')
        IndexError: list index out of range

    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.freebsd_e98484_salt/salt-call", line 15, in <module>
            salt_call()
          File "/var/tmp/.freebsd_e98484_salt/py2/salt/scripts.py", line 391, in salt_call
            client.run()
          File "/var/tmp/.freebsd_e98484_salt/py2/salt/cli/call.py", line 58, in run
            caller.run()
          File "/var/tmp/.freebsd_e98484_salt/py2/salt/cli/caller.py", line 134, in run
            ret = self.call()
          File "/var/tmp/.freebsd_e98484_salt/py2/salt/cli/caller.py", line 204, in call
            ret['return'] = func(*args, **kwargs)
          File "/var/tmp/.freebsd_e98484_salt/running_data/var/cache/salt/minion/extmods/modules/iocage.py", line 187, in list_releases
            return _display_list(_list('-r'))
          File "/var/tmp/.freebsd_e98484_salt/running_data/var/cache/salt/minion/extmods/modules/iocage.py", line 107, in _list
            if len(_) > 0])
          File "/var/tmp/.freebsd_e98484_salt/running_data/var/cache/salt/minion/extmods/modules/iocage.py", line 106, in <dictcomp>
            headers[k]: v for k, v in enumerate([_ for _ in l.split(' ')
        IndexError: list index out of range
```

**Comment by amendlik** [comment]
No one seems to be monitoring this repo for issues.
